### ISSUE TITLE
Failing trying to run examples/todos tests

### ISSUE THREAD

**Issue by RefuX** [reactjs/redux#1450]
I'm sure this is my local configuration but wanted to check. 
Running test results in:

```
/Users/jamesr/.nvm/versions/node/v4.2.6/bin/node /Users/jamesr/.nvm/versions/node/v4.2.6/bin/npm run-script test

redux-todos-example@0.0.0 test /Users/jamesr/WebstormProjects/redux/examples/todos
cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js


/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jamesr/WebstormProjects/redux/examples/todos/test/setup.js:3:14)
    at Module._compile (module.js:456:26)
    at loader (/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at args (/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/mocha/bin/_mocha:310:3)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/jamesr/WebstormProjects/redux/examples/todos/node_modules/mocha/bin/_mocha:309:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/jamesr/.nvm/versions/node/v4.2.6/bin/node" "/Users/jamesr/.nvm/versions/node/v4.2.6/bin/npm" "run-script" "test"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! redux-todos-example@0.0.0 test: `cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the redux-todos-example@0.0.0 test script 'cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js'.
npm ERR! This is most likely a problem with the redux-todos-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-todos-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesr/WebstormProjects/redux/examples/todos/npm-debug.log

Process finished with exit code 1
```

**Comment by gaearon** [comment]
Apparently this is the problem:

```
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
^
```

JSDom puts a template string there on purposes to warn users running earlier Node versions.
Which is weird because Node 4 definitely supports template strings.

I also installed Node 4.2.6 and could not reproduce. Can you try doing this?

```
dan@home ~/p/r/e/todos> node -v
v4.2.6
dan@home ~/p/r/e/todos> node
> `test`
'test'
> 
```

**Comment by gaearon** [comment]
I am not sure what the issue is but I don’t think this is something we need to fix here. The tests pass locally and on Travis so this is something related to your configuration.
