### ISSUE TITLE
TypeError: _dispatch is not a function

### ISSUE THREAD

**Issue by reggi** [reactjs/redux#1644]
Here's the error:

```
[1] TypeError: _dispatch is not a function
[1]     at Object.dispatch (/Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/redux/lib/applyMiddleware.js:45:18)
[1]     at /Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/react-router-redux/lib/index.js:90:13
[1]     at /Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/history/lib/useQueries.js:109:9
[1]     at /Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/history/lib/useBasename.js:84:9
[1]     at Object.listen (/Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/history/lib/createHistory.js:104:7)
[1]     at Object.listen (/Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/history/lib/useBasename.js:83:22)
[1]     at Object.listen (/Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/history/lib/useQueries.js:108:22)
[1]     at middleware (/Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/react-router-redux/lib/index.js:83:34)
[1]     at /Users/thomas/Desktop/react-redux-universal-hot-example/node_modules/redux/lib/applyMiddleware.js:49:16
[1]     at Array.map (native)
```

Seems that a default value was removed in a commit (https://github.com/reactjs/redux/commit/9496fd793bac83cedb643aba8da2c164aaf52a15) [11 days ago](https://github.com/reactjs/redux/commit/9496fd793bac83cedb643aba8da2c164aaf52a15).

[This line here](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js#L27) needs access to `dispatch` and it's undefined.

Here's how to recreate the error:

```
git clone https://github.com/erikras/react-redux-universal-hot-example.git
cd react-redux-universal-hot-example
npm install
npm run dev
```

**Comment by calvinnwq** [comment]
To get around this for now until it is fixed, you will want to use v3.4.0 instead of v3.5.0.

**Comment by simonelp** [comment]
The problem is `react-router-redux`, update version to 4.0.2 and edit your code

**Comment by TomiS** [comment]
Updating `react-router-redux` didn't solve it for me. I had to revert back to 3.4.0 to get my app working.

I thinks there is something weird in this file:
https://github.com/reactjs/redux/blob/v3.5.0/src/applyMiddleware.js#L27

In version 3.5.0 it was changed so that line 27 can potentially call empty variable set on line 22. Even if this is intentionally, it looks kinda weird to me.

**Comment by gaearon** [comment]
Thank you very much for reporting! Fixed in 3.5.1.

**Comment by andrewmclagan** [comment]
also encountered this issue, working as of 3.5.1 thanks! appreciated.

**Comment by khanhhaduc** [comment]
encountered the same issue, upgrading to 3.5.1 fixes perfectly. thanks for the promptly reply :)
