### ISSUE TITLE
Universal redux example not working?

### ISSUE THREAD

**Issue by Jezternz** [reactjs/redux#1656]
I attempted to run the universal redux example but it appears to fail. At first I thought it may be because I was running node 5, and not LTS, but after downgrading, it still fails with the same error. I followed the instructions on redux information site, calling npm install first.

I am using windows 7.

It appears to claim "Cannot find module" : 'babel-runtime/helpers/interop-require', I looked at this directory and indeed this file appears to be missing, possibly something need to be updated to path 'babel-runtime/helpers/interop-require-default' instead?

Full output:
```

> C:\work\redux\examples\universal>npm start
> 
> > redux-universal-example@0.0.0 start C:\work\redux\examples\universal
> > node server/index.js
> 
> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'babel-runtime/helpers/interop-require'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\work\redux\examples\universal\node_modules\babel-c
> ore\lib\api\node.js:7:23)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.4.3
> npm ERR! npm  v2.15.1
> npm ERR! code ELIFECYCLE
> npm ERR! redux-universal-example@0.0.0 start: `node server/index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the redux-universal-example@0.0.0 start script 'node server/i
> ndex.js'.
> npm ERR! This is most likely a problem with the redux-universal-example package,
> 
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server/index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs redux-universal-example
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls redux-universal-example
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\work\redux\examples\universal\npm-debug.log
```

**Comment by Jezternz** [comment]
Upon further investigation, I managed to get the example to run by updating all the babel-related dependencies:
```
{
  "name": "redux-universal-example",
  "version": "0.0.0",
  "description": "An example of a universally-rendered Redux application",
  "scripts": {
    "start": "node server/index.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/reactjs/redux.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/reactjs/redux/issues"
  },
  "homepage": "http://redux.js.org",
  "dependencies": {
    "babel-polyfill": "6.7.4",
    "babel-register": "6.7.2",
    "express": "^4.13.3",
    "qs": "^4.0.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.2.1",
    "redux": "^3.2.1",
    "redux-thunk": "^1.0.3",
    "serve-static": "^1.10.0"
  },
  "devDependencies": {
    "babel-core": "6.7.7",
    "babel-loader": "6.2.4",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-runtime": "6.6.1",
    "webpack": "^1.11.0",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.9.1"
  }
}
```

**Comment by gaearon** [comment]
Any chance it `npm install` just didn’t finish the first time, e.g. due to a network error?

**Comment by Jezternz** [comment]
Weird, just tried again from scratch, and didn't have any problems. Sorry for wasting your time :)

**Comment by gaearon** [comment]
No problem. Happy it worked. npm can be flaky sometimes.
