### ISSUE TITLE
Unable to build v3.5.2

### ISSUE THREAD

**Issue by thaggie** [reactjs/redux#1845]
Environment:
* `node --version` -> v6.3.0
* `npm --version` -> 3.10.3

Repro steps:
```
git clone https://github.com/reactjs/redux.git
cd redux
git checkout v3.5.2
npm install
```

Results:
```
> redux@3.5.2 build:umd:min /Users/thaggie/dev/deps/redux
> cross-env BABEL_ENV=commonjs NODE_ENV=production webpack src/index.js dist/redux.min.js

Hash: da6adf72cbf2038a3555
Version: webpack 1.13.1
Time: 838ms
       Asset     Size  Chunks             Chunk Names
redux.min.js  6.64 kB       0  [emitted]  main
    + 13 hidden modules
/Users/thaggie/dev/deps/redux/node_modules/jstransform/src/jstransform.js:270
    throw e;
    ^

Error: Parse Error: Line 5: Illegal export declaration
    at throwError (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2823:21)
    at throwErrorTolerant (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2835:24)
    at parseSourceElement (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6432:17)
    at parseProgramElement (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6491:16)
    at parseProgramElements (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6523:29)
    at parseProgram (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6536:16)
    at Object.parse (/Users/thaggie/dev/deps/redux/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7713:23)
    at getAstForSource (/Users/thaggie/dev/deps/redux/node_modules/jstransform/src/jstransform.js:244:21)
    at Object.transform (/Users/thaggie/dev/deps/redux/node_modules/jstransform/src/jstransform.js:267:11)
    at Function.transform (/Users/thaggie/dev/deps/redux/node_modules/es3ify/index.js:108:24)
```

The actual command that fails is:
```
node ./build/es3ify
```

**Comment by gaearon** [comment]
Breaking change somewhere? We'd want to kill `es3ify` anyway and replace it with appropriate Babel plugins.

**Comment by SimenB** [comment]
`es3ify` is removed already (#1688), but wasn't at the time of the last release.
I'm guessing it fails as it globs up `es` as well (https://github.com/reactjs/redux/blob/v3.5.2/build/es3ify.js#L5). Maybe jstransform was nicer before spicyj/es3ify#11?

**Comment by thaggie** [comment]
Thanks
