### ISSUE TITLE
Getting unexpected token while running todos example

### ISSUE THREAD

**Issue by sp-suresh** [reactjs/redux#2423]
I was trying to run todos example code, but it's failing on `npm start`, throwing following error:

```
suresh@SP:~/redux/examples/todos $ npm start

> todos@0.0.1 start /Users/suresh/redux/examples/todos
> react-scripts start

/Users/suresh/redux/examples/todos/node_modules/react-scripts/scripts/start.js:31
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! todos@0.0.1 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todos@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suresh/.npm/_logs/2017-05-24T07_49_34_725Z-debug.log
```
Here is log details

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/suresh/.nvm/versions/node/v4.5.0/bin/node',
1 verbose cli   '/Users/suresh/.nvm/versions/node/v4.5.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle todos@0.0.1~prestart: todos@0.0.1
6 silly lifecycle todos@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle todos@0.0.1~start: todos@0.0.1
8 verbose lifecycle todos@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle todos@0.0.1~start: PATH: /Users/suresh/.nvm/versions/node/v4.5.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/suresh/redux/examples/todos/node_modules/.bin:/usr/local/Cellar/bison/3.0.4/bin:/usr/local/sbin:/usr/local/geoserver-2.9.1/bin:/Users/suresh/geomesa-accumulo_2.11-1.3.0/bin:/Users/suresh/accumulo-1.8.0/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/suresh/.nvm/versions/node/v4.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/hadoop/2.7.3/libexec/bin:/Users/suresh/Library/Android/sdk/tools:/Users/suresh/Library/Android/sdk/platform-tools
10 verbose lifecycle todos@0.0.1~start: CWD: /Users/suresh/redux/examples/todos
11 silly lifecycle todos@0.0.1~start: Args: [ '-c', 'react-scripts start' ]
12 silly lifecycle todos@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle todos@0.0.1~start: Failed to exec start script
14 verbose stack Error: todos@0.0.1 start: `react-scripts start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/suresh/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/suresh/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid todos@0.0.1
16 verbose cwd /Users/suresh/redux/examples/todos
17 verbose Darwin 16.6.0
18 verbose argv "/Users/suresh/.nvm/versions/node/v4.5.0/bin/node" "/Users/suresh/.nvm/versions/node/v4.5.0/bin/npm" "start"
19 verbose node v4.5.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error todos@0.0.1 start: `react-scripts start`
23 error Exit status 1
24 error Failed at the todos@0.0.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
What is going wrong?

**Comment by sp-suresh** [comment]
It seems that It's not able to identify destructuring syntax.

**Comment by jimbolla** [comment]
> info using node@v4.5.0

[You’ll need to have Node >= 6 on your machine. ](https://github.com/facebookincubator/create-react-app#installation)

**Comment by sp-suresh** [comment]
That's Solved the issue.....
