### ISSUE TITLE
Asynchronous sample code does not work.

### ISSUE THREAD

**Issue by nabezokodaikon** [reactjs/redux#2438]
Execution of the code of [this page](http://redux.js.org/docs/advanced/ExampleRedditAPI.html) causes 'TypeError middleware is not a function' error and it does not work. What should I do?

```
/Users/nabezokodaikon/develop/redux-async-sample/node_modules/redux/lib/applyMiddleware.js:49
        return middleware(middlewareAPI);
               ^

TypeError: middleware is not a function
    at /Users/nabezokodaikon/develop/redux-async-sample/node_modules/redux/lib/applyMiddleware.js:49:16
    at Array.map (native)
    at /Users/nabezokodaikon/develop/redux-async-sample/node_modules/redux/lib/applyMiddleware.js:48:27
    at createStore (/Users/nabezokodaikon/develop/redux-async-sample/node_modules/redux/lib/createStore.js:65:33)
    at configureStore (/Users/nabezokodaikon/develop/redux-async-sample/build/configureStore.js:27:33)
    at Object.<anonymous> (/Users/nabezokodaikon/develop/redux-async-sample/build/containers/Root.js:31:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by nabezokodaikon** [comment]
Solved.
It seems that how to import createlogger was wrong.

sample code.
```
import createLogger from 'redux-logger'
```

correct code
```
import { createLogger } from "redux-logger";
```
