### ISSUE TITLE
'undefined is not a function' only when creating release build for Android

### ISSUE THREAD

**Issue by johndanek** [reactjs/redux#2477]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Running my React Native (& Ignite) app on dev build works totally fine. But, when I attempt to assembleRelease and install a production version of the app, it crashes on a device immediately upon opening. The Java stack trace for failure is:

```
06-27 13:52:32.618 16961-16990/? E/ReactNativeJS: undefined is not a function (evaluating '(0,l.combineReducers)({github:r(851).reducer,login:r(852).reducer,search:r(905).reducer})')
06-27 13:52:32.618 16961-16991/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.johntest, PID: 16961
                                                   com.facebook.react.common.JavascriptException: undefined is not a function (evaluating '(0,l.combineReducers)({github:r(851).reducer,login:r(852).reducer,search:r(905).reducer})'), stack:
                                                   default@691:231
                                                   <unknown>@913:672
                                                   o@2:565
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@12:45
                                                   o@2:565
                                                   i@2:278
                                                   t@2:210
                                                   global code@1443:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.facebook.react.cxxbridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:199)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Attempt to install an Ignite React Native signed APK onto an Android hardware device and run it.

**What is the expected behavior?**
It shouldn't crash immediately.

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**
Redux: 3.7.1
React Native: 0.45.1

**Comment by markerikson** [comment]
I'll be honest, I highly doubt this is an actual issue with Redux, and also that there's anything we can do about it.  This is much more likely to be an issue related to React Native and its build process somehow.

**Comment by johndanek** [comment]
I think you're correct, but thanks for looking!
